### ISSUE TITLE
Make a Dub package

### ISSUE THREAD

**Issue by cyrusmsk** [DmitryOlshansky/rewind-regex#3]
Hi @DmitryOlshansky!

Do you think the package is ready for public real life usage?
If so, maybe you can add it to dub-registry (code.dlang.org website) so users will be able to use the package with just dub add rewind-ragex?

**Comment by DmitryOlshansky** [comment]
Too early for that need parser first and bytecode interpreter next.

Вс, 25 июня 2023 г. в 12:49, Serg Gini ***@***.***>:

**Comment by cyrusmsk** [comment]
Ok. Thanks
